resolver: nightly-2018-06-14

ghc-options:
  "$locals": -fwarn-unused-binds -fwarn-unused-matches -fwarn-unused-imports

packages:
  - src/ast
  - src/backend-ghc
  - src/rewrite
  - src/prettyprint
  - src/refactor
  - src/builtin-refactorings
  - src/experimental-refactorings
  - demo
  - src/cli
  - src/debug
  - src/daemon

extra-deps:
  - fswatch-0.1.0.3
  - knob-0.1.1
  - classyplate-0.3.1.0
  - minisat-solver-0.1
  - portable-lines-0.1
